apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: large-pod-test
  name: large-pod-test
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 800
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: large-pod-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: large-pod-test
    spec:
      automountServiceAccountToken: false
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        args:
        - sleep
        - "1000000"
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox-2
        args:
        - sleep
        - "1000000"
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
